// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjtrycepjhffkuzpdudj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqdHJ5Y2VwamhmZmt1enBkdWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzQwMTYsImV4cCI6MjA2MjE1MDAxNn0.qsm85Xd_8sCIxMQocqErk54_00BkqU01Lod2_g3fDmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);